import type { Metadata } from "next";
import { Cairo } from "next/font/google";
import "./globals.css";
import { ModalProvider } from "@/components/providers/ModalProvider";
import { ToastProvider } from "@/components/providers/ToastProvider";
const cairo = Cairo({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Daily Check Up System",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" dir="rtl">
      <body className={`${cairo.className} bg-neutral-100`}>
        <ToastProvider />
        <ModalProvider />
        {children}
      </body>
    </html>
  );
}
